"""add_client_table

Revision ID: 3490223047ce
Revises: 828f12d5956a
Create Date: 2026-05-09 17:19:43.363714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3490223047ce'
down_revision = '828f12d5956a'
branch_labels = None
depends_on = None


def upgrade():
    # === Create clients table (missing from auto-generated migration) ===
    op.create_table('clients',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)

    # Add client_id column to users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('users_client_id_fkey', 'clients', ['client_id'], ['id'])

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_api_tokens_token'))

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)


    with op.batch_alter_table('custom_field_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_custom_field_values_ticket'))

    with op.batch_alter_table('escalation_logs', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('kb_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_kb_articles_slug'))

    with op.batch_alter_table('kb_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_kb_categories_slug'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('sla_policies', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('ticket_history', schema=None) as batch_op:
        batch_op.alter_column('field_changed',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('old_value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('new_value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('ticket_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('project',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('attachment',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('tickets_original_assignee_fkey'), type_='foreignkey')
        batch_op.drop_column('original_assignee')

    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_time_entries_ticket'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('project',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('avatar',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('otp_backup_codes')
        batch_op.drop_column('otp_secret')
        batch_op.drop_column('otp_enabled')

    # ### end Alembic commands ###


def downgrade():
    # === Drop clients table ===
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_client_id_fkey', type_='foreignkey')
        batch_op.drop_column('client_id')
    op.drop_table('clients')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otp_secret', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otp_backup_codes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('avatar',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('project',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_time_entries_ticket'), ['ticket_id'], unique=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_assignee', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('tickets_original_assignee_fkey'), 'users', ['original_assignee'], ['id'])
        batch_op.alter_column('attachment',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('project',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('ticket_number',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('ticket_history', schema=None) as batch_op:
        batch_op.alter_column('new_value',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('old_value',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('field_changed',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('sla_policies', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('kb_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_kb_categories_slug'), ['slug'], unique=False)

    with op.batch_alter_table('kb_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_kb_articles_slug'), ['slug'], unique=False)

    with op.batch_alter_table('escalation_logs', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('custom_field_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_custom_field_values_ticket'), ['ticket_id'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_api_tokens_token'), ['token'], unique=False)

    # ### end Alembic commands ###
