"""add project column

Revision ID: 828f12d5956a
Revises: 
Create Date: 2026-05-05 18:02:39.683921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828f12d5956a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('project')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('project')

    # ### end Alembic commands ###
