"""add sla fields to client and ticket models

Revision ID: b835da9262b1
Revises: 3490223047ce
Create Date: 2026-05-10 23:55:20.388192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b835da9262b1'
down_revision = '3490223047ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_time_hours', sa.Numeric(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('resolution_time_hours', sa.Numeric(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('business_hours_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('active_sla', sa.Boolean(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('clients_name_key'), type_='unique')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_state', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('sla_state')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('clients_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('active_sla')
        batch_op.drop_column('business_hours_only')
        batch_op.drop_column('resolution_time_hours')
        batch_op.drop_column('response_time_hours')

    # ### end Alembic commands ###
